SELECT YMD.PAY_YMD, PAY.EMP_ID, PAY.PSUM, PAY.PSUM1, PAY.PSUM2, PAY.DSUM, PAY.TSUM, PAY.REAL_AMT, DTL.GAMT, DTL.DAMT, DTL.TAMT
  FROM PAY_PAYROLL PAY
  JOIN PAY_PAY_YMD YMD
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  JOIN (SELECT PAY_PAYROLL_ID
             , ISNULL(SUM(CASE WHEN PAY_ITEM_TYPE_CD='PAY_G' THEN CAL_MON ELSE 0 END),0) AS GAMT
             , ISNULL(SUM(CASE WHEN PAY_ITEM_TYPE_CD='DEDUCT' THEN CAL_MON ELSE 0 END),0) AS DAMT
             , ISNULL(SUM(CASE WHEN PAY_ITEM_TYPE_CD='TAX' THEN CAL_MON ELSE 0 END),0) AS TAMT
		 FROM PAY_PAYROLL_DETAIL  GROUP BY PAY_PAYROLL_ID) DTL
    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
 WHERE YMD.COMPANY_CD='X'
   AND PAY_YM='202009'
-- ORDER BY YMD.PAY_YMD, PAY.PAY_PAYROLL_ID
