/**
 * ToBe에 중복이 되는 급여항목코드 추출
 */
DECLARE @fr_company nvarchar(10) = 'A' -- 'A', 'M'
      , @to_company nvarchar(10) = 'Y' -- 'I', 'Y'
--SELECT DISTINCT CD_COMPANY, ITEM_CD, ITEM_NM
--FROM (
--SELECT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, D.ITEM_CD, D.ITEM_NM
--FROM dwehrdev.dbo.H_MONTH_SUPPLY A
--JOIN CNV_PAY_ITEM B
--ON A.CD_COMPANY=B.COMPANY_CD
--AND A.CD_ALLOW = B.CD_ITEM
--AND B.TP_CODE='1'
--JOIN (
--	SELECT COMPANY_CD, ITEM_CD, ITEM_NM
--	FROM CNV_PAY_ITEM
--	WHERE ITEM_CD > ' ' AND COMPANY_CD BETWEEN @fr_company AND @to_company
--	AND TP_CODE='1'
--	GROUP BY COMPANY_CD, ITEM_CD, ITEM_NM
--	HAVING COUNT(*) > 1
--	) D
--ON B.COMPANY_CD = D.COMPANY_CD AND B.ITEM_CD=D.ITEM_CD
--WHERE YM_PAY >= '201501'
--AND A.CD_COMPANY BETWEEN @fr_company AND @to_company
--GROUP BY A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, D.ITEM_CD, D.ITEM_NM
--HAVING COUNT(*) > 1
--) T1
--ORDER BY CD_COMPANY, ITEM_CD
-- 공제항목체크
SELECT DISTINCT CD_COMPANY, ITEM_CD, ITEM_NM
FROM (
SELECT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, D.ITEM_CD, D.ITEM_NM
FROM dwehrdev.dbo.H_MONTH_DEDUCT A
JOIN CNV_PAY_ITEM B
ON A.CD_COMPANY=B.COMPANY_CD
AND A.CD_DEDUCT = B.CD_ITEM
AND B.TP_CODE='2'
JOIN (
	SELECT COMPANY_CD, ITEM_CD, ITEM_NM
	FROM CNV_PAY_ITEM
	WHERE ITEM_CD > ' ' AND COMPANY_CD BETWEEN @fr_company AND @to_company
	AND TP_CODE='2'
	GROUP BY COMPANY_CD, ITEM_CD, ITEM_NM
	HAVING COUNT(*) > 1
	) D
ON B.COMPANY_CD = D.COMPANY_CD AND B.ITEM_CD=D.ITEM_CD
WHERE YM_PAY >= '201501'
AND A.CD_COMPANY BETWEEN @fr_company AND @to_company
GROUP BY A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, D.ITEM_CD, D.ITEM_NM
HAVING COUNT(*) > 1
) T1
ORDER BY CD_COMPANY, ITEM_CD