---- 급여지급유형
--/*TRUNCATE TABLE CNV_PAY_TYPE*/
--INSERT INTO CNV_PAY_TYPE(
--COMPANY_CD,
--CD_PAYGP,
--FG_SUPP,
--GROUP_KIND,
--NM_PAYGP,
--OLD_PAYGP,
--NM_SUPP
--)
SELECT CD_COMPANY, CD_PAYGP, FG_SUPP
	 , (SELECT SYS_CD FROM FRM_CODE WHERE COMPANY_CD=CD_COMPANY AND CD_KIND='PAY_GROUP_CD' AND CD=CD_PAYGP /*AND GETDATE() BETWEEN STA_YMD AND END_YMD*/) GROUP_KIND
	 , (SELECT CD_NM FROM FRM_CODE WHERE COMPANY_CD=CD_COMPANY AND CD_KIND='PAY_GROUP_CD' AND CD=CD_PAYGP /*AND GETDATE() BETWEEN STA_YMD AND END_YMD*/) GROUP_KIND
	 , dbo.F_FRM_CODE_NM(CD_COMPANY, 'KO', 'PAY_GROUP_CD', CD_PAYGP, dbo.XF_SYSDATE(0), '1') NM_PAYGP
	 , (SELECT NM_DETAIL FROM dwehr_hrd.dbo.B_DETAIL_CODE where CD_MASTER = 'HU187' AND CD_DETAIL=CD_PAYGP) OLD_PAYGP
	 , (SELECT NM_DETAIL FROM dwehr_hrd.dbo.B_DETAIL_CODE where CD_MASTER = 'HU109' AND CD_DETAIL=FG_SUPP) NM_SUPP
  FROM (
		SELECT DISTINCT CD_COMPANY, CD_PAYGP, FG_SUPP--, TP_DUTY --, TP_CALC_PAY--, FG_PERSON, TP_CALC_INS--tp_calc_ins
			  -- ,dbo.F_FRM_CODE_NM(CD_COMPANY, 'KO', 'PAY_GROUP_CD', CD_PAYGP, dbo.XF_SYSDATE(0), '1') NM_PAYGP
		  FROM dwehr_hrd.dbo.H_MONTH_PAY_BONUS
		 WHERE 1=1
		   --AND YM_PAY LIKE '201902'
		   AND YM_PAY > '2014'
		   AND CD_COMPANY = 'M'
		   --AND YN_PAY_CLOSE = 'N'
		   AND CD_PAYGP != 'EA01'
		   AND CD_PAYGP != 'HA01'
		) A
		--WHERE CD_PAYGP='X005'
	ORDER BY CD_COMPANY, CD_PAYGP-- dbo.F_FRM_CODE_NM(CD_COMPANY, 'KO', 'PAY_GROUP_CD', CD_PAYGP, dbo.XF_SYSDATE(0), 'O') 
	, FG_SUPP

--SELECT CNV_PAY_TYPE_ID,
--COMPANY_CD,
--CD_PAYGP,
--FG_SUPP,
--ISNULL(GROUP_KIND,''),
--ISNULL(NM_PAYGP,''),
--ISNULL(OLD_PAYGP,''),
--ISNULL(NM_SUPP,''),
--ISNULL(PAY_TYPE_CD,''),
--ISNULL(SYS_CD,'')
--FROM CNV_PAY_TYPE
--ORDER BY CNV_PAY_TYPE_ID