SELECT HIS.KEY_CD1 AS CD
     , DBO.F_FRM_CODE_NM('E', 'KO', 'PAY_ITEM_CD', HIS.KEY_CD1, GETDATE(), '1') AS CD_NM
  FROM FRM_UNIT_STD_MGR MGR
       INNER JOIN FRM_UNIT_STD_HIS HIS
               ON MGR.FRM_UNIT_STD_MGR_ID = HIS.FRM_UNIT_STD_MGR_ID
              AND GETDATE() BETWEEN HIS.STA_YMD AND HIS.END_YMD
              AND MGR.UNIT_CD = 'PAY'
              AND MGR.STD_KIND = 'PAY_ITEM_CD_BASE'
 WHERE MGR.COMPANY_CD = 'E'
   AND EXISTS (SELECT 1 FROM DBO.FN_SPLIT_ARRAY(STUFF('|PAY_PAY|DEDUCT|TAX|', 1, 1, ''), '|') WHERE Items = HIS.CD1)
 --ORDER BY DBO.F_FRM_CODE_NM(:company_cd, :locale_cd, 'PAY_ITEM_CD', HIS.KEY_CD1, GETDATE(), 'O')