-- 지급항목
SELECT  DISTINCT CD_COMPANY, YM_PAY, ITEM_CD, ITEM_NM
  FROM (
		SELECT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, B.ITEM_CD, B.ITEM_NM
		  FROM dwehrdev.dbo.H_MONTH_SUPPLY A
		  JOIN CNV_PAY_ITEM B
			ON A.CD_COMPANY = B.COMPANY_CD
		   AND A.CD_COMPANY NOT IN ('O','D','L','Z')
		   AND A.CD_ALLOW = B.CD_ITEM
		   AND B.TP_CODE = '1'
		 WHERE A.YM_PAY >= '201501'
		 GROUP BY A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, B.ITEM_CD, B.ITEM_NM
		 HAVING COUNT(*) > 1
		 ) A

SELECT CD_ALLOW, MIN(YM_PAY), MAX(YM_PAY)
FROM dwehrdev.dbo.H_MONTH_SUPPLY
WHERE CD_COMPANY='I'
AND CD_ALLOW IN ('011','018')
GROUP BY CD_ALLOW

---- 공제항목
--SELECT  DISTINCT CD_COMPANY, YM_PAY, ITEM_CD, ITEM_NM
--  FROM (
--		SELECT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, B.ITEM_CD, B.ITEM_NM
--		  FROM dwehrdev.dbo.H_MONTH_DEDUCT A
--		  JOIN CNV_PAY_ITEM B
--			ON A.CD_COMPANY = B.COMPANY_CD
--		   AND A.CD_COMPANY NOT IN ('O','D','L','Z')
--		   AND A.CD_DEDUCT = B.CD_ITEM
--		   AND B.TP_CODE = '2'
--		 WHERE A.YM_PAY >= '201501'
--		 GROUP BY A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.NO_PERSON, B.ITEM_CD, B.ITEM_NM
--		 HAVING COUNT(*) > 1
--		 ) A

--SELECT CD_DEDUCT, MIN(YM_PAY), MAX(YM_PAY)
--FROM dwehrdev.dbo.H_MONTH_DEDUCT
--WHERE CD_COMPANY='F'
--AND CD_DEDUCT IN ('7502','7503')
--GROUP BY CD_DEDUCT