--SELECT *
--FROM CNV_PAY_ITEM
--WHERE CD_ITEM='7201'
--;
--INSERT INTO PAY_ATTACH_REF(
--PAY_ATTACH_REF_ID, -- 압류공제id
--EMP_ID, -- 사원id
--PAY_YMD, -- 급여일자
--PAY_TYPE_CD, -- 급여지급유형코드(PAY_TYPE_CD 급여, 상여)
--ATTCH_YMD, -- 공제일자
--DEDUCTION_MON, -- 공제금액
--MOD_USER_ID, -- 변경자
--MOD_DATE, -- 변경일시
--TZ_CD, -- 타임존코드
--TZ_DATE -- 타임존일시
--)
SELECT --NEXT VALUE FOR S_PAY_SEQUENCE,
	PAY.EMP_ID, PAY_YMD, PAY_TYPE_CD, PAY_YMD ATTCH_YMD, CAL_MON, 0, DTL.MOD_DATE, DTL.TZ_CD, DTL.TZ_DATE
FROM PAY_PAY_YMD YMD
JOIN PAY_PAYROLL PAY
ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
JOIN PAY_PAYROLL_DETAIL DTL
ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
WHERE YMD.COMPANY_CD='F'
AND DTL.PAY_ITEM_CD='D110'
AND YMD.PAY_YM ='201912'
AND YMD.PAY_YMD='20191230'
AND PAY.EMP_ID IN (SELECT EMP_ID FROM PHM_EMP WHERE COMPANY_CD='F' AND EMP_NO IN ('20130699','20160262'))
AND YMD.PAY_YM < '202105'
--ORDER BY EMP_ID, PAY_YMD DESC