-- 업데이트 SALARY_TYPE_CD
select TOP 100 PAY.SALARY_TYPE_CD, DTL.SALARY_TYPE_CD
--UPDATE DTL SET SALARY_TYPE_CD = PAY.SALARY_TYPE_CD
from PAY_PAY_YMD YMD
join PAY_PAYROLL PAY
ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
JOIN PAY_PAYROLL_DETAIL DTL
ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
WHERE YMD.PAY_YM >= '202001'
AND PAY.SALARY_TYPE_CD > ''
AND PAY.SALARY_TYPE_CD != ISNULL(DTL.SALARY_TYPE_CD,'N/A')