SELECT pay.* -- SALARY_TYPE_CD -- PAY_BAS_TYPE_CD	기본금산정방식[PAY_BAS_TYPE_CD]
--UPDATE PAY SET SALARY_TYPE_CD = B.SALARY_TYPE_CD, PAY_BAS_TYPE_CD=B.BP12
--UPDATE PAY set CONT_TIME = B.BP05
FROM PAY_PAY_YMD YMD
JOIN PAY_PAYROLL PAY
ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
JOIN CNM_CNT B -- SALARY_TYPE_CD -- BP12	기본급산정유형코드[PAY_BAS_TYPE_CD]
ON YMD.COMPANY_CD = B.COMPANY_CD
AND B.EMP_ID = PAY.EMP_ID
AND GETDATE() BETWEEN B.STA_YMD AND B.END_YMD
WHERE YMD.COMPANY_CD = 'F'
AND YMD.PAY_YMD BETWEEN '20210101' AND '20210531'
					 --  AND PAY.EMP_ID=446356
;

-- 업데이트 SALARY_TYPE_CD
select COUNT(*)--TOP 100 PAY.SALARY_TYPE_CD, DTL.SALARY_TYPE_CD
--UPDATE DTL SET SALARY_TYPE_CD = PAY.SALARY_TYPE_CD
from PAY_PAY_YMD YMD
join PAY_PAYROLL PAY
ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
JOIN PAY_PAYROLL_DETAIL DTL
ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
WHERE YMD.PAY_YM >= '202001' AND YMD.PAY_YM<='202105' -- 128396
AND YMD.COMPANY_CD='F'
AND PAY.SALARY_TYPE_CD > ''
AND PAY.SALARY_TYPE_CD != ISNULL(DTL.SALARY_TYPE_CD,'N/A')

;