SELECT LEFT(A.QUERY_NAME,3) JOB_DIVISION,
       QUERY_NAME,
	   DISPLAY_NAME,
	   B.CREATE_TIME
FROM FRM_QUERY_DEF A
JOIN FRM_QUERY_DEF_BODY B
ON A.QUERY_DEF_ID = B.QUERY_DEF_ID
WHERE A.QUERY_NAME LIKE 'REP%'
--      LEFT(A.QUERY_NAME,3) IN ('HSI',
--'NHS',
--'MEE',
--'ECC',
--'CAT',
--'LOM',
--'RSF',
--'CHD',
--'CLB',
--'HBM',
--'IAI',
--'STP',
--'EMI',
--'PEB',
--'REP',
--'PAY',
--'TBS',
--'SCE',
--'RWP')
AND (B.QUERY_STRING LIKE '%CTZ_NO%'
     OR B.QUERY_STRING LIKE '%ACCOUNT_NO%')
ORDER BY A.QUERY_NAME