declare @company_cd nvarchar(10) = 'F'
declare @locale_cd nvarchar(10) = 'KO'
declare @pay_ym nvarchar(10) = '202105'
declare @def_ym nvarchar(10) = '202104'
declare @pay_type_cd nvarchar(10) = '120'
;
WITH CTE AS (
    SELECT STD.COMPANY_CD
         , STD.LOCALE_CD
         , NULL AS PAY_ITEM_CD
         , '10' AS ORD_NO
         , '10' AS ITEM_TYPE
         , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(STD.LOCALE_CD, 'TERM', '인원'), '인원') AS ITEM_TYPE_NM
         , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(STD.LOCALE_CD, 'TERM', 'EMP_CNT'), '지급인원') AS PAY_ITEM_NM
         , COUNT(CASE WHEN YMD.PAY_YM = STD.BEF_YM THEN ROLL.EMP_ID ELSE NULL END) AS BEF_MON
         , COUNT(CASE WHEN YMD.PAY_YM = STD.CUR_YM THEN ROLL.EMP_ID ELSE NULL END) AS CUR_MON
         , COUNT(CASE WHEN YMD.PAY_YM = STD.CUR_YM THEN ROLL.EMP_ID ELSE NULL END) AS CUR_PER_MON
         , MAX(STD.BEF_YM) AS BEF_YM
    	 , MAX(STD.CUR_YM) AS CUR_YM
    	 , MAX(STD.PAY_TYPE_CD) AS PAY_TYPE_CD
      FROM (SELECT @company_cd AS COMPANY_CD
                 , @locale_cd AS LOCALE_CD
                 , @pay_ym AS CUR_YM
                 , CONVERT(NVARCHAR(6), DATEADD(D, -1, CONVERT(DATE, @pay_ym + '01')), 112) AS BEF_YM
                 , @pay_type_cd AS PAY_TYPE_CD
           ) STD
           INNER JOIN PAY_PAY_YMD YMD
                   ON STD.COMPANY_CD = YMD.COMPANY_CD
                  AND STD.PAY_TYPE_CD = YMD.PAY_TYPE_CD
                  AND (STD.CUR_YM = YMD.PAY_YM OR STD.BEF_YM = YMD.PAY_YM)
                  AND YMD.PAY_YM IN (STD.CUR_YM , STD.BEF_YM)
           INNER JOIN PAY_PAYROLL ROLL
                   ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
     GROUP BY STD.COMPANY_CD, STD.LOCALE_CD
 )
SELECT M.COMPANY_CD
     , M.LOCALE_CD
	 , M.ORD_NO    -- 10(인원), 20(지급), 30(공제)
     , M.ITEM_TYPE -- 10(인원), 20(고정급여), 30(변동급여), 40(과세액), 50(공제액), 60(그외)
     , M.PAY_ITEM_CD
     , CASE WHEN M.ITEM_TYPE = '10' THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '인원'), '인원')
            WHEN M.ITEM_TYPE = '20' THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '고정급여'), '고정급여')
            WHEN M.ITEM_TYPE = '30' THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '변동급여'), '변동급여')
            WHEN M.ITEM_TYPE IN ('25', '35') THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '소계'), '소계')
            WHEN M.ITEM_TYPE = '36' THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '합계'), '합계')
            WHEN M.ITEM_TYPE IN ('40', '50', '60') THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '공제내역'), '공제내역')
            WHEN M.ITEM_TYPE = '65' THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '공제금액합계'), '공제금액합계')
            WHEN M.ITEM_TYPE = '70' THEN ISNULL(DBO.F_FRM_GET_TERM(@locale_cd, 'TERM', '실지급액'), '실지급액')
       END AS ITEM_TYPE_NM
     , M.PAY_ITEM_NM
     , M.BEF_MON
     , M.CUR_MON
     , M.CUR_PER_MON
     , CASE WHEN M.CUR_MON - M.BEF_MON > 0 THEN '▲'
            WHEN M.CUR_MON - M.BEF_MON = 0 THEN '-'
            ELSE '▼'
       END AS UP_DOWN
     , M.CUR_MON - M.BEF_MON AS DIFF_MON
     , CASE WHEN M.BEF_MON = 0 AND M.CUR_MON = 0 THEN 0
            WHEN M.BEF_MON = 0 THEN 100
			ELSE DBO.XF_CEIL( ( (M.CUR_MON - M.BEF_MON) / M.BEF_MON ) * 100, 2 )
       END AS DIFF_RATE
  FROM (
SELECT COMPANY_CD
     , LOCALE_CD
     , PAY_ITEM_CD
     , ORD_NO
     , ITEM_TYPE
     , PAY_ITEM_NM
     , BEF_MON
     , CUR_MON
     , CUR_PER_MON
  FROM CTE

UNION ALL

SELECT CTE.COMPANY_CD
     , CTE.LOCALE_CD
     , DTL.PAY_ITEM_CD
     , CASE WHEN DTL.PAY_ITEM_TYPE_CD IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G') THEN '20' -- 지급
            ELSE '30'  -- 공제
       END AS ORD_NO
     , CASE WHEN ISNULL(ITEM.YN_FIX, 'N') = 'Y' THEN '20'  -- 고정지급
            ELSE 
                 CASE WHEN DTL.PAY_ITEM_TYPE_CD IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G') THEN '30'  --변동지급
                      WHEN DTL.PAY_ITEM_TYPE_CD IN ('TAX') THEN '40'   -- 과세
                      WHEN DTL.PAY_ITEM_TYPE_CD IN ('DEDUCT') THEN '50'  -- 공제
                      ELSE '60'
                 END
       END AS ITEM_TYPE
     --, DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(CTE.LOCALE_CD, 'TERM', '고정급여'), '고정급여') AS ITEM_TYPE_NM
     , DBO.F_FRM_CODE_NM(CTE.COMPANY_CD, CTE.LOCALE_CD, 'PAY_ITEM_CD', DTL.PAY_ITEM_CD, MAX(YMD.PAY_YMD), '1') AS PAY_ITEM_NM
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.BEF_YM THEN ISNULL(DTL.CAL_MON, 0) ELSE 0 END) AS BEF_MON
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ISNULL(DTL.CAL_MON, 0) ELSE 0 END) AS CUR_MON
	 , CASE WHEN SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) = 0 THEN 0
	        ELSE ROUND(SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) / MAX(CTE.CUR_MON), 0, 0)
	   END AS PRE_PER_MON
  FROM CTE
       INNER JOIN PAY_PAY_YMD YMD
               ON CTE.COMPANY_CD = YMD.COMPANY_CD
              AND CTE.PAY_TYPE_CD = YMD.PAY_TYPE_CD
              AND (CTE.CUR_YM = YMD.PAY_YM OR CTE.BEF_YM = YMD.PAY_YM)
              AND YMD.PAY_YM IN (CTE.CUR_YM , CTE.BEF_YM)
       INNER JOIN PAY_PAYROLL ROLL
               ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
       INNER JOIN PAY_PAYROLL_DETAIL DTL
               ON ROLL.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
              AND DTL.PAY_ITEM_TYPE_CD IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G', 'DEDUCT', 'TAX', 'TAX_N_P')
       LEFT OUTER JOIN PAY_ITEM_MST ITEM
               ON YMD.COMPANY_CD = ITEM.COMPANY_CD
              AND DTL.PAY_ITEM_CD = ITEM.PAY_ITEM_CD
              AND YMD.PAY_YMD BETWEEN ITEM.STA_YMD AND ITEM.END_YMD
 GROUP BY CTE.COMPANY_CD
        , CTE.LOCALE_CD
        , ITEM.YN_FIX
        , DTL.PAY_ITEM_TYPE_CD
        , DTL.PAY_ITEM_CD

UNION ALL

SELECT CTE.COMPANY_CD
     , CTE.LOCALE_CD
     , NULL AS PAY_ITEM_CD
     , '20' AS ORD_NO -- 지급
     , '25' AS ITEM_TYPE -- 고정지급소계
     , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(CTE.LOCALE_CD, 'TERM', '소계'), '소계') AS PAY_ITEM_NM
     --, DBO.F_FRM_CODE_NM(CTE.COMPANY_CD, CTE.LOCALE_CD, 'PAY_ITEM_CD', DTL.PAY_ITEM_CD, MAX(YMD.PAY_YMD), '1') AS PAY_ITEM_NM
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.BEF_YM THEN DTL.CAL_MON ELSE 0 END) AS BEF_MON
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) AS CUR_MON
	 , CASE WHEN SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) = 0 THEN 0
	        ELSE ROUND(SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) / MAX(CTE.CUR_MON), 0, 0)
	   END AS PRE_PER_MON
  FROM CTE
       INNER JOIN PAY_PAY_YMD YMD
               ON CTE.COMPANY_CD = YMD.COMPANY_CD
              AND CTE.PAY_TYPE_CD = YMD.PAY_TYPE_CD
              AND (CTE.CUR_YM = YMD.PAY_YM OR CTE.BEF_YM = YMD.PAY_YM)
              AND YMD.PAY_YM IN (CTE.CUR_YM , CTE.BEF_YM)
       INNER JOIN PAY_PAYROLL ROLL
               ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
       INNER JOIN PAY_PAYROLL_DETAIL DTL
               ON ROLL.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
              AND DTL.PAY_ITEM_TYPE_CD IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G')
       INNER JOIN PAY_ITEM_MST ITEM
               ON YMD.COMPANY_CD = ITEM.COMPANY_CD
              AND DTL.PAY_ITEM_CD = ITEM.PAY_ITEM_CD
              AND YMD.PAY_YMD BETWEEN ITEM.STA_YMD AND ITEM.END_YMD
			  AND ISNULL(ITEM.YN_FIX, 'N') = 'Y'
 GROUP BY CTE.COMPANY_CD
        , CTE.LOCALE_CD

UNION ALL

SELECT CTE.COMPANY_CD
     , CTE.LOCALE_CD
     , NULL AS PAY_ITEM_CD
     , '20' AS ORD_NO -- 지급
     , '35' AS ITEM_TYPE -- 변동지급소계
     , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(CTE.LOCALE_CD, 'TERM', '소계'), '소계') AS PAY_ITEM_NM
     --, DBO.F_FRM_CODE_NM(CTE.COMPANY_CD, CTE.LOCALE_CD, 'PAY_ITEM_CD', DTL.PAY_ITEM_CD, MAX(YMD.PAY_YMD), '1') AS PAY_ITEM_NM
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.BEF_YM THEN DTL.CAL_MON ELSE 0 END) AS BEF_MON
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) AS CUR_MON
	 , CASE WHEN SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) = 0 THEN 0
	        ELSE ROUND(SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN DTL.CAL_MON ELSE 0 END) / MAX(CTE.CUR_MON), 0, 0)
	   END AS PRE_PER_MON
  FROM CTE
       INNER JOIN PAY_PAY_YMD YMD
               ON CTE.COMPANY_CD = YMD.COMPANY_CD
              AND CTE.PAY_TYPE_CD = YMD.PAY_TYPE_CD
              AND (CTE.CUR_YM = YMD.PAY_YM OR CTE.BEF_YM = YMD.PAY_YM)
              AND YMD.PAY_YM IN (CTE.CUR_YM , CTE.BEF_YM)
       INNER JOIN PAY_PAYROLL ROLL
               ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
       INNER JOIN PAY_PAYROLL_DETAIL DTL
               ON ROLL.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
              AND DTL.PAY_ITEM_TYPE_CD IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G')
       INNER JOIN PAY_ITEM_MST ITEM
               ON YMD.COMPANY_CD = ITEM.COMPANY_CD
              AND DTL.PAY_ITEM_CD = ITEM.PAY_ITEM_CD
              AND YMD.PAY_YMD BETWEEN ITEM.STA_YMD AND ITEM.END_YMD
			  AND ISNULL(ITEM.YN_FIX, 'N') <> 'Y'
 GROUP BY CTE.COMPANY_CD
        , CTE.LOCALE_CD

UNION ALL

SELECT CTE.COMPANY_CD
     , CTE.LOCALE_CD
     , NULL AS PAY_ITEM_CD
     , '20' AS ORD_NO -- 지급
     , '36' AS ITEM_TYPE -- 지급합계
     , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(CTE.LOCALE_CD, 'TERM', '합계'), '합계') AS PAY_ITEM_NM
     --, DBO.F_FRM_CODE_NM(CTE.COMPANY_CD, CTE.LOCALE_CD, 'PAY_ITEM_CD', DTL.PAY_ITEM_CD, MAX(YMD.PAY_YMD), '1') AS PAY_ITEM_NM
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.BEF_YM THEN ROLL.PSUM2 ELSE 0 END) AS BEF_MON
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.PSUM2 ELSE 0 END) AS CUR_MON
	 , CASE WHEN SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.PSUM2 ELSE 0 END) = 0 THEN 0
	        ELSE ROUND(SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.PSUM2 ELSE 0 END) / MAX(CTE.CUR_MON), 0, 0)
	   END AS PRE_PER_MON
  FROM CTE
       INNER JOIN PAY_PAY_YMD YMD
               ON CTE.COMPANY_CD = YMD.COMPANY_CD
              AND CTE.PAY_TYPE_CD = YMD.PAY_TYPE_CD
              AND (CTE.CUR_YM = YMD.PAY_YM OR CTE.BEF_YM = YMD.PAY_YM)
              AND YMD.PAY_YM IN (CTE.CUR_YM , CTE.BEF_YM)
       INNER JOIN PAY_PAYROLL ROLL
               ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
 GROUP BY CTE.COMPANY_CD
        , CTE.LOCALE_CD

UNION ALL

SELECT CTE.COMPANY_CD
     , CTE.LOCALE_CD
     , NULL AS PAY_ITEM_CD
     , '30' AS ORD_NO -- 공제
     , '65' AS ITEM_TYPE -- 공제금액합계
     , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(CTE.LOCALE_CD, 'TERM', '공제금액합계'), '공제금액합계') AS PAY_ITEM_NM
     --, DBO.F_FRM_CODE_NM(CTE.COMPANY_CD, CTE.LOCALE_CD, 'PAY_ITEM_CD', DTL.PAY_ITEM_CD, MAX(YMD.PAY_YMD), '1') AS PAY_ITEM_NM
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.BEF_YM THEN ROLL.DSUM + ROLL.TSUM ELSE 0 END) AS BEF_MON
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.DSUM + ROLL.TSUM ELSE 0 END) AS CUR_MON
	 , CASE WHEN SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.DSUM + ROLL.TSUM ELSE 0 END) = 0 THEN 0
	        ELSE ROUND(SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.DSUM + ROLL.TSUM ELSE 0 END) / MAX(CTE.CUR_MON), 0, 0)
	   END AS PRE_PER_MON
  FROM CTE
       INNER JOIN PAY_PAY_YMD YMD
               ON CTE.COMPANY_CD = YMD.COMPANY_CD
              AND CTE.PAY_TYPE_CD = YMD.PAY_TYPE_CD
              AND (CTE.CUR_YM = YMD.PAY_YM OR CTE.BEF_YM = YMD.PAY_YM)
              AND YMD.PAY_YM IN (CTE.CUR_YM , CTE.BEF_YM)
       INNER JOIN PAY_PAYROLL ROLL
               ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
 GROUP BY CTE.COMPANY_CD
        , CTE.LOCALE_CD

UNION ALL

SELECT CTE.COMPANY_CD
     , CTE.LOCALE_CD
     , NULL AS PAY_ITEM_CD
     , '40' AS ORD_NO -- 실지급액
     , '70' AS ITEM_TYPE -- 실지급액
     , DBO.XF_NVL_C(DBO.F_FRM_GET_TERM(CTE.LOCALE_CD, 'TERM', '실지급액'), '실지급액') AS PAY_ITEM_NM
     --, DBO.F_FRM_CODE_NM(CTE.COMPANY_CD, CTE.LOCALE_CD, 'PAY_ITEM_CD', DTL.PAY_ITEM_CD, MAX(YMD.PAY_YMD), '1') AS PAY_ITEM_NM
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.BEF_YM THEN ROLL.REAL_AMT ELSE 0 END) AS BEF_MON
	 , SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.REAL_AMT ELSE 0 END) AS CUR_MON
	 , CASE WHEN SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.REAL_AMT ELSE 0 END) = 0 THEN 0
	        ELSE ROUND(SUM(CASE WHEN YMD.PAY_YM = CTE.CUR_YM THEN ROLL.REAL_AMT ELSE 0 END) / MAX(CTE.CUR_MON), 0, 0)
	   END AS PRE_PER_MON
  FROM CTE
       INNER JOIN PAY_PAY_YMD YMD
               ON CTE.COMPANY_CD = YMD.COMPANY_CD
              AND CTE.PAY_TYPE_CD = YMD.PAY_TYPE_CD
              AND (CTE.CUR_YM = YMD.PAY_YM OR CTE.BEF_YM = YMD.PAY_YM)
              AND YMD.PAY_YM IN (CTE.CUR_YM , CTE.BEF_YM)
       INNER JOIN PAY_PAYROLL ROLL
               ON YMD.PAY_YMD_ID = ROLL.PAY_YMD_ID
 GROUP BY CTE.COMPANY_CD
        , CTE.LOCALE_CD
) M
 ORDER BY M.ORD_NO, M.ITEM_TYPE, DBO.F_FRM_CODE_NM(M.COMPANY_CD, M.LOCALE_CD, 'PAY_ITEM_CD', M.PAY_ITEM_CD, GETDATE(), 'O')