--SELECT *
--FROM FRM_FILE_BIZ_GUIDE

alter table dbo.FRM_FILE_BIZ_GUIDE drop constraint AK_FRM_FILE_BIZ_GUIDE;
alter table dbo.FRM_FILE_BIZ_GUIDE add constraint AK_FRM_FILE_BIZ_GUIDE UNIQUE NONCLUSTERED (OBJECT_ID, ORD_NO, COMPANY_CD);

alter table dbo.FRM_EXECUTABLE_OBJECT drop constraint AK_FRM_EXECUTABLE_OBJECT;
alter table dbo.FRM_EXECUTABLE_OBJECT add constraint AK_FRM_EXECUTABLE_OBJECT UNIQUE NONCLUSTERED (OBJECT_NM);

-- FRM_FILE_BIZ_GUIDE에 디폴드 회사코드 넣기
select *
-- UPDATE A SET COMPANY_CD = 'E'
from FRM_FILE_BIZ_GUIDE A
--WHERE COMPANY_CD IS NULL

-- FRM_FILE_BIZ_GUIDE 엔터티수정
-- FRM0001_00_R01 SQL 수정