
--COM0000_00_R01
--2020.11.04 상진 FRM_AUTH_USER_BINDING, FRM_USER_GROUP_MAP 테이블에 
--USER에 대한 권한 데이터를 INSERT 시켜도 데이터가 나오지 않아 일단 주석, 계열사도 중복으로 나와
--그룹핑 함
SELECT A.COMPANY_CD
      ,A.COMPANY_NM 
  FROM (
				SELECT     B.COMPANY_CD
				         , C.COMPANY_NM 
				      FROM FRM_AUTH_ITEM A 
				           INNER JOIN FRM_AUTH_COMPANY_BINDING  B ON ( A.AUTH_ITEM_ID = B.AUTH_ITEM_ID )
				           INNER JOIN FRM_COMPANY C ON ( B.COMPANY_CD = C.COMPANY_CD )
				           INNER JOIN FRM_AUTH_USER_BINDING D ON ( A.AUTH_ITEM_ID  = D.AUTH_ITEM_ID )
				     WHERE A.AUTH_ITEM_TYPE = '04'
				       --AND B.COMPANY_CD <>   'R'   
				       AND D.USER_ID  =   6639947  
				     UNION 
				    SELECT B.COMPANY_CD
				         , C.COMPANY_NM 
				      FROM FRM_AUTH_ITEM A 
				           INNER JOIN FRM_AUTH_COMPANY_BINDING  B ON ( A.AUTH_ITEM_ID = B.AUTH_ITEM_ID )
				           INNER JOIN FRM_COMPANY C ON ( B.COMPANY_CD = C.COMPANY_CD )
				           INNER JOIN FRM_USERGROUP_AUTH_MAP D ON ( A.AUTH_ITEM_ID  = D.AUTH_ITEM_ID )
				           INNER JOIN FRM_USER_GROUP_MAP E ON ( A.COMPANY_CD  = E.COMPANY_CD  AND D.USERGROUP_ID = E.USERGROUP_ID )
				     WHERE A.AUTH_ITEM_TYPE = '04'
				       --AND B.COMPANY_CD <>   'R'   
				       AND E.USER_ID  =   6639947 
		) A
 GROUP BY COMPANY_CD , COMPANY_NM

