        SELECT PAY_GROUP_ID, PAY_GROUP
		     , dbo.F_FRM_CODE_NM( COMPANY_CD, 'KO', 'PAY_GROUP_CD', PAY_GROUP, dbo.XF_SYSDATE(0), '1') AS PAY_GROUP_NM -- Á÷À§
			 , COMPANY_CD
		     , ITEM_TYPE
             , ITEM_COND
             , ITEM_VALS
			 , dbo.F_FRM_CODE_NM( COMPANY_CD, 'KO', 'PAY_GROUP_CD', PAY_GROUP, dbo.XF_SYSDATE(0), 'O')
          FROM PAY_GROUP WITH (NOLOCK)
          UNPIVOT ( ITEM_TYPE FOR ITEM_TYPE_COL IN (ITEM_TYPE1, ITEM_TYPE2, ITEM_TYPE3, ITEM_TYPE4, ITEM_TYPE5) )  UNPVT1
          UNPIVOT ( ITEM_COND FOR ITEM_COND_COL IN (ITEM_COND1, ITEM_COND2, ITEM_COND3, ITEM_COND4, ITEM_COND5) )  UNPVT2
          UNPIVOT ( ITEM_VALS FOR ITEM_VALS_COL IN (ITEM_VALS1, ITEM_VALS2, ITEM_VALS3, ITEM_VALS4, ITEM_VALS5) )  UNPVT3
         WHERE (1=1)
		   --AND PAY_GROUP_ID = @an_pay_group_id
           AND RIGHT(ITEM_TYPE_COL,1)  = RIGHT(ITEM_COND_COL, 1)
           AND RIGHT(ITEM_COND_COL,1)  = RIGHT(ITEM_VALS_COL, 1)
           AND RIGHT(ITEM_VALS_COL,1)  = RIGHT(ITEM_TYPE_COL, 1)
		   AND COMPANY_CD = 'E'
		   --AND dbo.F_FRM_CODE_NM( COMPANY_CD, 'KO', 'PAY_GROUP_CD', PAY_GROUP, dbo.XF_SYSDATE(0), 'S') = '01'
		 ORDER BY dbo.F_FRM_CODE_NM( COMPANY_CD, 'KO', 'PAY_GROUP_CD', PAY_GROUP, dbo.XF_SYSDATE(0), 'O')
;
