;
 with cte as (
	 select SUPER_ORG_ID, ORG_ID, STA_YMD, END_YMD
	 from VI_FRM_ORM_ORG
	 where '20200131' BETWEEN STA_YMD AND END_YMD
	 --AND ORG_ID=59672
	   AND COMPANY_CD='F'
	 UNION ALL
	 SELECT A.SUPER_ORG_ID, A.ORG_ID, A.STA_YMD, A.END_YMD
	 from VI_FRM_ORM_ORG A
	 JOIN CTE 
	   ON A.ORG_ID = cte.SUPER_ORG_ID
	  AND ('20200131' BETWEEN A.STA_YMD AND A.END_YMD
		OR '20210131' BETWEEN A.STA_YMD AND A.END_YMD
	  )
	 where cte.SUPER_ORG_ID IS NOT NULL
 )
 SELECT DISTINCT CTE.SUPER_ORG_ID, CTE.ORG_ID, B.STA_YMD, B.END_YMD
 FROM CTE
 LEFT OUTER JOIN VI_FRM_ORM_ORG B
   ON cte.ORG_ID = B.ORG_ID
  AND '20210131' BETWEEN B.STA_YMD AND B.END_YMD
ORDER BY ORG_ID
