-- PAY1046 pay1046.jsp
SELECT PAY_ITEM_CD, PAY_ITEM_TYPE_CD, PRINT_ORD_NO
     , 'DBO.XF_NVL_N(SUM(CASE WHEN PAY_ITEM_CD = '''+ PAY_ITEM_CD +''' THEN CAL_MON END),0) '  +
		 ' AS col' + CAST( ROW_NUMBER() OVER( ORDER BY PRINT_ORD_NO ) AS NVARCHAR ) AS SQL_COL
  FROM (
SELECT KEY_CD1 AS PAY_ITEM_CD
          		, CD1 AS PAY_ITEM_TYPE_CD 
          		, DBO.XF_TO_NUMBER(ETC_CD4) AS PRINT_ORD_NO
          		, STA_YMD
          		, END_YMD
           FROM FRM_UNIT_STD_MGR MGR,
                   FRM_UNIT_STD_HIS HIS
           WHERE MGR.FRM_UNIT_STD_MGR_ID = HIS.FRM_UNIT_STD_MGR_ID
             AND MGR.COMPANY_CD =  'E' 
             AND MGR.UNIT_CD =  'PAY'
             AND MGR.STD_KIND = 'PAY_ITEM_CD_BASE'
             --AND (CD1 IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G', 'DEDUCT', 'TAX', 'TAX_N_P'))
             AND (CD1 IN ('PAY_PAY', 'PAY', 'PAY_GN', 'PAY_G', 'DEDUCT', 'TAX', 'TAX_N_P'))
	) A
	ORDER BY PRINT_ORD_NO, PAY_ITEM_CD