SELECT DATEPART(YY, DT_PROV) YEAR, COUNT(*) CNT
  FROM CNV_PAY_DTL_SAP
 GROUP BY DATEPART(YY,DT_PROV)
 ORDER BY DATEPART(YY,DT_PROV)

UPDATE A
SET EMP_ID = EMP.EMP_ID
FROM CNV_PAY_DTL_SAP A
JOIN PHM_EMP EMP
ON A.EMP_NO = EMP.EMP_NO
AND EMP.COMPANY_CD='F'

UPDATE A
SET CD_PAYGP = B.CD
FROM CNV_PAY_DTL_SAP A
JOIN FRM_CODE B
ON A.NM_PAYGP = B.CD_NM
AND B.COMPANY_CD='F'
AND B.CD_KIND = 'PAY_GROUP_CD'

UPDATE A
SET CD_PAYGP = 'F21'
FROM CNV_PAY_DTL_SAP A
WHERE NM_PAYGP='F&B 판매'

SELECT *
UPDATE A
SET CD_PAYGP = B.CD
FROM CNV_PAY_TYPE_SAP A
JOIN FRM_CODE B
ON A.NM_PAYGP = B.CD_NM
AND B.COMPANY_CD='F'
AND B.CD_KIND = 'PAY_GROUP_CD'

UPDATE A
SET CD_PAYGP = 'F21'
FROM CNV_PAY_TYPE_SAP A
WHERE NM_PAYGP='F&B 판매'

SELECT *
UPDATE A
SET PAY_TYPE_CD = B.CD
  , SYS_CD = B.SYS_CD
FROM CNV_PAY_TYPE_SAP A
JOIN FRM_CODE B
ON A.PAY_TYPE_NM = B.CD_NM
AND B.COMPANY_CD='F'
AND B.CD_KIND = 'PAY_TYPE_CD'
AND A.PAY_TYPE_CD IS NULL

UPDATE A
SET PAY_TYPE_NM='직원' + PAY_TYPE_NM
FROM CNV_PAY_TYPE_SAP A
WHERE PAY_TYPE_CD IS NULL
AND PAY_TYPE_NM LIKE '성과급%'

UPDATE A
SET PAY_TYPE_NM= REPLACE(PAY_TYPE_NM, '생상', '생산')
FROM CNV_PAY_TYPE_SAP A
WHERE PAY_TYPE_CD IS NULL
AND PAY_TYPE_NM LIKE '%생상'

UPDATE A
SET PAY_TYPE_NM= REPLACE(PAY_TYPE_NM, '정기소급_정읍', '정기소급_정읍생산')
FROM CNV_PAY_TYPE_SAP A
WHERE PAY_TYPE_CD IS NULL
AND PAY_TYPE_NM LIKE '정기소급_정읍'

UPDATE A
SET PAY_TYPE_NM= REPLACE(PAY_TYPE_NM, '퇴직월급여_광진생산', '퇴직월급여_강진생산')
FROM CNV_PAY_TYPE_SAP A
WHERE PAY_TYPE_CD IS NULL
AND PAY_TYPE_NM LIKE '퇴직월급여_광진생산'

UPDATE A
SET PAY_TYPE_NM= REPLACE(PAY_TYPE_NM, '제수당소급_SC', '정기소급_SC')
FROM CNV_PAY_TYPE_SAP A
WHERE PAY_TYPE_CD IS NULL
AND PAY_TYPE_NM LIKE '제수당소급_SC'

SELECT *--PAY_TYPE_NM, REPLACE(PAY_TYPE_NM, '생상', '생산')
FROM CNV_PAY_TYPE_SAP
WHERE PAY_TYPE_CD IS NULL
;

SELECT *
FROM CNV_PAY_TYPE_SAP A
JOIN CNV_PAY_DTL_SAP B
ON A.CD_PAYGP = B.CD_PAYGP
AND A.SAP_KIND1 = B.SAP_KIND1
AND A.SAP_KIND2 = B.SAP_KIND2
AND A.DT_PROV = B.DT_PROV
;
WITH CTE AS (
SELECT DT_PROV, CD_PAYGP, NM_PAYGP, SAP_KIND1, SAP_KIND2
FROM CNV_PAY_DTL_SAP
EXCEPT
SELECT DT_PROV, CD_PAYGP, NM_PAYGP, SAP_KIND1, SAP_KIND2
FROM CNV_PAY_TYPE_SAP
--2016-12-31	F31	창원생산	A	
--2018-11-30	F32	성남생산	B	
--2017-10-31	F42	정읍생산	A	
)
SELECT *
FROM CNV_PAY_DTL_SAP A
JOIN CTE B
ON A.DT_PROV = B.DT_PROV
AND A.CD_PAYGP = B.CD_PAYGP
AND A.SAP_KIND1 = B.SAP_KIND1
AND A.SAP_KIND2 = B.SAP_KIND2
ORDER BY A.DT_PROV
