SELECT COUNT(*)
FROM PAY_ACNT_MNG_DUP

SELECT COUNT(*)
FROM PAY_ACNT_MNG

SELECT 
				A.ACNT_7 CD_ITEM,
				(SELECT NM_ITEM FROM CNV_PAY_ITEM WHERE COMPANY_CD=A.COMPANY_CD AND CD_ITEM=A.ACNT_7) AS NM_ITEM,
       A.*
  FROM PAY_ACNT_MNG_DUP A
 WHERE COMPANY_CD + PAY_TYPE_CD + PAY_ITEM_CD + PAY_ACNT_TYPE_CD IN
				 (
					SELECT COMPANY_CD + PAY_TYPE_CD + PAY_ITEM_CD + PAY_ACNT_TYPE_CD
					FROM (
						SELECT DISTINCT COMPANY_CD, PAY_TYPE_CD, PAY_ITEM_CD, PAY_ACNT_TYPE_CD, A.EMP_ACNT_CD, A.EXC_ACNT_CD, A.OFFSET_ANCT_CD
						FROM PAY_ACNT_MNG_DUP A
					) A
					GROUP BY COMPANY_CD, PAY_TYPE_CD, PAY_ITEM_CD, PAY_ACNT_TYPE_CD
					HAVING COUNT(*) > 1
				)
 ORDER BY COMPANY_CD, PAY_TYPE_CD, PAY_ITEM_CD, PAY_ACNT_TYPE_CD, ACNT_7