INSERT INTO ORM_BIZ_TYPE(ORM_BIZ_TYPE_ID,
ORM_BIZ_INFO_ID,
BIZ_TYPE_CD,
STA_YMD,
END_YMD,
NOTE,
MOD_USER_ID,
MOD_DATE,
TZ_CD,
TZ_DATE
)
SELECT NEXT VALUE FOR S_ORM_SEQUENCE, -- ORM_BIZ_TYPE_ID,
ORM_BIZ_INFO_ID,
'PAY' BIZ_TYPE_CD,
'19000101' STA_YMD,
'29991231' END_YMD,
'' NOTE,
0 MOD_USER_ID,
GETDATE() MOD_DATE,
'KST' TZ_CD,
GETDATE() TZ_DATE
FROM ORM_BIZ_INFO A WHERE COMPANY_CD!='F' 
AND NOT EXISTS (SELECT * FROM ORM_BIZ_TYPE WHERE ORM_BIZ_INFO_ID = A.ORM_BIZ_INFO_ID AND BIZ_TYPE_CD='PAY')
