DECLARE @company_cd nvarchar(10) = 'X'
SELECT *
FROM FRM_CODE
WHERE CD_KIND = 'PAY_GROUP_CD'
AND COMPANY_CD=@company_cd
ORDER BY CD

SELECT *
FROM FRM_CODE
WHERE CD_KIND = 'PAY_TYPE_CD'
AND COMPANY_CD=@company_cd
ORDER BY CD

SELECT *
FROM dwehrdev.dbo.B_DETAIL_CODE_COMPANY
WHERE CD_COMPANY=@company_cd
AND CD_MASTER='HU109'

