declare @company_cd nvarchar(10)
      , @update_pay_type_cd nvarchar(10) = 'Y' -- 급여유형업데이트
	  , @update_cnt_payroll nvarchar(10) = 'Y' -- ToBe대상건수
set @company_cd = 'X'
--SELECT @update_pay_type_cd = 'N'
--SELECT @update_cnt_payroll = 'N'
-- 급여유형 UPDATE
if @update_pay_type_cd = 'Y'
	UPDATE A
	   SET PAY_TYPE_CD = ISNULL(B.PAY_TYPE_CD,'')
	  FROM CNV_PAY_YMD_CNT A
	  LEFT OUTER JOIN CNV_PAY_TYPE B
		ON A.CD_COMPANY = B.COMPANY_CD
	   AND A.FG_SUPP = B.FG_SUPP
	   AND A.CD_PAYGP = B.CD_PAYGP
	 WHERE A.CD_COMPANY=@company_cd

if @update_cnt_payroll = 'Y'
	UPDATE A
	   SET A.CNV_PAY = B.CNV_PAY
	     , A.CNV_PAY_EMP = B.CNV_PAY_EMP
	  FROM CNV_PAY_YMD_CNT A
	  JOIN (SELECT T1.CD_COMPANY, T1.DT_PROV, T1.PAY_TYPE_CD, COUNT(*) CNV_PAY, COUNT(DISTINCT NO_PERSON) CNV_PAY_EMP
	           FROM CNV_PAY_YMD_CNT T1
			   INNER  JOIN dwehrdev.dbo.H_MONTH_PAY_BONUS T2
						ON T1.CD_COMPANY = T2.CD_COMPANY
					   AND T1.DT_PROV = T2.DT_PROV
					   AND T1.FG_SUPP = T2.FG_SUPP
					   AND T1.YM_PAY = T2.YM_PAY
					   AND T1.CD_PAYGP = T2.CD_PAYGP
				GROUP BY T1.CD_COMPANY, T1.DT_PROV, T1.PAY_TYPE_CD) B
		 ON A.CD_COMPANY = B.CD_COMPANY
		 AND A.DT_PROV = B.DT_PROV
		 AND A.PAY_TYPE_CD = B.PAY_TYPE_CD
	 WHERE A.CD_COMPANY = @company_cd
SELECT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.CD_PAYGP, A.CNT_PAY, A.PAY_TYPE_CD, A.CNV_PAY, A.CNV_PAY_EMP
  FROM CNV_PAY_YMD_CNT A
 WHERE A.CD_COMPANY=@company_cd
 AND (CNV_PAY != CNT_PAY
      OR A.PAY_TYPE_CD=''
	  OR CD_PAYGP=''
	  OR CD_PAYGP IN (SELECT CD FROM FRM_CODE WHERE CD_KIND='PAY_GROUP_CD' AND COMPANY_CD=@company_cd AND SYS_CD='02')
	  )
 AND ( @company_cd != 'I' OR
		( YM_PAY < '201500' AND CD_PAYGP LIKE 'IB%' OR YM_PAY > '201500') )
 ORDER BY A.CD_COMPANY, A.DT_PROV, A.CD_PAYGP, A.FG_SUPP