/**
 * AsIs기준으로 급여일자확인
 */
DECLARE @cd_company nvarchar(10) = 'T'
-- 
INSERT INTO CNV_PAY_YMD (CD_COMPANY, YM_PAY, FG_SUPP, DT_PROV, PAY_TYPE_CD)
SELECT DISTINCT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, ISNULL(C.PAY_TYPE_CD,'')
FROM dwehrdev.dbo.H_MONTH_PAY_BONUS a
LEFT OUTER JOIN CNV_PAY_TYPE C (NOLOCK)
    ON A.CD_COMPANY = C.COMPANY_CD
	   AND A.CD_PAYGP = C.CD_PAYGP
	   AND A.FG_SUPP = C.FG_SUPP
WHERE A.CD_COMPANY like ISNULL(@cd_company, '') + '%'
EXCEPT
SELECT CD_COMPANY, YM_PAY, FG_SUPP, DT_PROV, PAY_TYPE_CD
FROM CNV_PAY_YMD
;
SELECT CD_COMPANY, YM_PAY, FG_SUPP, DT_PROV, PAY_TYPE_CD
FROM CNV_PAY_YMD
WHERE CD_COMPANY='T'
--SELECT A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, A.PAY_TYPE_CD, ISNULL(A.ALTER_PAY_TYPE_CD,'') AS ALTER_PAY_TYPE_CD
--FROM CNV_PAY_YMD A
--INNER JOIN (
--		SELECT CD_COMPANY, DT_PROV, PAY_TYPE_CD
--		  FROM CNV_PAY_YMD
--		 WHERE CD_COMPANY = @cd_company
--		 GROUP BY CD_COMPANY, DT_PROV, PAY_TYPE_CD
--		 HAVING COUNT(*) > 1
--	 ) B
--ON B.CD_COMPANY = A.CD_COMPANY
--		   AND B.DT_PROV = A.DT_PROV
--		   AND B.PAY_TYPE_CD = A.PAY_TYPE_CD
--ORDER BY A.CD_COMPANY, A.DT_PROV, YM_PAY

----SELECT *
----FROM CNV_PAY_YMD
----WHERE CD_COMPANY = @cd_company
