--SELECT *
--  FROM PAY_PAY_YMD YMD
--  JOIN PAY_PAYROLL PAY
--    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
--  LEFT OUTER JOIN PAY_PAYROLL_DETAIL DTL
--    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
-- WHERE COMPANY_CD='E'
--   AND PAY_YM='202010'
--   --AND DTL.PAY_PAYROLL_DETAIL_ID IS NULL
--;

--SELECT TOP 100 ID_UPDATE,dbo.F_CNV_GET_EMP_ID_FROM_ASIS_LOGINID(A.ID_UPDATE)
--FROM dwehrdev.dbo.H_MONTH_PAY_BONUS A
--WHERE CD_COMPANY='F'
--AND YM_PAY='201501'

--SELECT DISTINCT ID_INSERT, ID_CALCU, ID_UPDATE,dbo.F_CNV_GET_EMP_ID_FROM_ASIS_LOGINID(A.ID_UPDATE)
--FROM dwehrdev.dbo.H_MONTH_SUPPLY A
--WHERE CD_COMPANY='B'
--AND YM_PAY='201901'