
INSERT INTO CNV_PAY_YMD_CNT
(CD_COMPANY,
YM_PAY,
FG_SUPP,
DT_PROV,
CD_PAYGP,
CNT_PAY)
select CD_COMPANY, YM_PAY, FG_SUPP, DT_PROV, ISNULL(CD_PAYGP,'') CD_PAYGP, COUNT(*) CNT_PAY
from dwehrdev.dbo.H_MONTH_PAY_BONUS A
GROUP BY A.CD_COMPANY, A.YM_PAY, A.FG_SUPP, A.DT_PROV, ISNULL(A.CD_PAYGP,'')
;

--select TOP 10 CD_COMPANY, YM_PAY, FG_SUPP, DT_PROV, ISNULL(CD_PAYGP,'') CD_PAYGP, HIS.GROUP_CD
--from dwehrdev.dbo.H_MONTH_PAY_BONUS A
--left outer join (SELECT COMPANY_CD, EMP_NO, DBO.F_PAY_GROUP_CD(EMP_ID) AS GROUP_CD FROM PHM_EMP_NO_HIS) his 
--on A.CD_COMPANY = his.COMPANY_CD
--and A.NO_PERSON = his.EMP_NO
--WHERE YM_PAY='201501'
--AND A.CD_COMPANY='H'

UPDATE A
SET A.CNT_SUPPLY = B.DTL_CNT
FROM CNV_PAY_YMD_CNT A
JOIN (SELECT H.CD_COMPANY, H.YM_PAY, H.FG_SUPP, H.DT_PROV, ISNULL(H.CD_PAYGP,'') CD_PAYGP, COUNT(*) DTL_CNT
        FROM dwehrdev.dbo.H_MONTH_PAY_BONUS H
		JOIN dwehrdev.dbo.H_MONTH_SUPPLY D
		  ON H.CD_COMPANY = D.CD_COMPANY
		 AND H.YM_PAY = D.YM_PAY
		 AND H.FG_SUPP = D.FG_SUPP
		 AND H.DT_PROV = D.DT_PROV
		 AND H.NO_PERSON = D.NO_PERSON
	GROUP BY H.CD_COMPANY, H.YM_PAY, H.FG_SUPP, H.DT_PROV, ISNULL(H.CD_PAYGP,'')
	) B
ON A.CD_COMPANY = B.CD_COMPANY
AND A.YM_PAY = B.YM_PAY
AND A.FG_SUPP = B.FG_SUPP
AND A.DT_PROV = B.DT_PROV
AND A.CD_PAYGP = B.CD_PAYGP
;

UPDATE A
SET A.CNT_DEDUCT = B.DTL_CNT
FROM CNV_PAY_YMD_CNT A
JOIN (SELECT H.CD_COMPANY, H.YM_PAY, H.FG_SUPP, H.DT_PROV, ISNULL(H.CD_PAYGP,'') CD_PAYGP, COUNT(*) DTL_CNT
        FROM dwehrdev.dbo.H_MONTH_PAY_BONUS H
		JOIN dwehrdev.dbo.H_MONTH_DEDUCT D
		  ON H.CD_COMPANY = D.CD_COMPANY
		 AND H.YM_PAY = D.YM_PAY
		 AND H.FG_SUPP = D.FG_SUPP
		 AND H.DT_PROV = D.DT_PROV
		 AND H.NO_PERSON = D.NO_PERSON
	GROUP BY H.CD_COMPANY, H.YM_PAY, H.FG_SUPP, H.DT_PROV, ISNULL(H.CD_PAYGP,'')
	) B
ON A.CD_COMPANY = B.CD_COMPANY
AND A.YM_PAY = B.YM_PAY
AND A.FG_SUPP = B.FG_SUPP
AND A.DT_PROV = B.DT_PROV
AND A.CD_PAYGP = B.CD_PAYGP
;
