SELECT TOP 1000 A.NM_PAYGP, A.CD_PAYGP, C.CD_NM, C.CD
--UPDATE A SET CD_PAYGP = C.CD
FROM CNV_PAY_DTL_SAP_RETIRE A
JOIN FRM_CODE C
ON C.CD_KIND = 'PAY_GROUP_CD'
AND C.COMPANY_CD='F'
AND C.LOCALE_CD='KO'
AND A.NM_PAYGP = CD_NM

SELECT DISTINCT CD_PAYGP, NM_PAYGP
-- UPDATE A SET CD_PAYGP = 'F21'
FROM CNV_PAY_DTL_SAP_RETIRE A
WHERE CD_PAYGP IS NULL
AND NM_PAYGP='F&B ÆÇ¸Å'

SELECT *
--UPDATE A SET EMP_ID = EMP.EMP_ID
FROM CNV_PAY_DTL_SAP_RETIRE A
JOIN PHM_EMP EMP
ON EMP.COMPANY_CD='F'
AND A.EMP_NO = EMP.EMP_NO

UPDATE A SET AMT2 = AMT
FROM CNV_PAY_DTL_SAP_RETIRE A

SELECT *
UPDATE A SET AMT = -AMT2
FROM CNV_PAY_DTL_SAP_RETIRE A
JOIN CNV_PAY_ITEM B
ON B.COMPANY_CD = 'F'
AND A.CD_ITEM = B.CD_ITEM
WHERE B.SAP_SIGN = -1



