SELECT B.COMPANY_CD, B.EMP_ID, B.EMP_NO
FROM PAY_ATTACH_REF A
JOIN PHM_EMP B
ON A.EMP_ID = B.EMP_ID
WHERE B.COMPANY_CD = 'I'

INSERT INTO PAY_ATTACH_REF (PAY_ATTACH_REF_ID, -- 압류공제id
		EMP_ID, -- 사원id
		PAY_YMD, -- 급여일자
		PAY_TYPE_CD, -- 급여지급유형코드(PAY_TYPE_CD 급여, 상여)
		ATTCH_YMD, -- 공제일자
		DEDUCTION_MON, -- 공제금액
		MOD_USER_ID, -- 변경자
		MOD_DATE, -- 변경일시
		TZ_CD, -- 타임존코드
		TZ_DATE -- 타임존일시
)
SELECT  NEXT VALUE FOR S_PAY_SEQUENCE AS PAY_ATTACH_REF_ID, -- 압류공제id
		PAY.EMP_ID, -- 사원id
		YMD.PAY_YMD, -- 급여일자
		YMD.PAY_TYPE_CD, -- 급여지급유형코드(PAY_TYPE_CD 급여, 상여)
		YMD.PAY_YMD ATTCH_YMD, -- 공제일자
		DTL.CAL_MON	DEDUCTION_MON, -- 공제금액
		DTL.MOD_USER_ID	MOD_USER_ID, -- 변경자
		DTL.MOD_DATE	MOD_DATE, -- 변경일시
		DTL.TZ_CD	TZ_CD, -- 타임존코드
		DTL.TZ_DATE	TZ_DATE -- 타임존일시
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  JOIN PAY_PAYROLL_DETAIL DTL
    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
  JOIN PHM_EMP EMP
    ON PAY.EMP_ID = EMP.EMP_ID
 WHERE YMD.COMPANY_CD='I'
   AND PAY_ITEM_CD = 'D110'
   AND EMP.IN_OFFI_YN ='Y'
---- 81건 Insert

SELECT *
FROM PAY_ATTACH_REF
