SELECT X01_SUM
     , ISNULL(CAL.F0310, 0)           AS CAL_INCOM_AMT	-- 家垫技_沥魂
     , ISNULL(CAL.F0320, 0)           AS CAL_INHBT_AMT	-- 林刮技_沥魂
FROM INT_Y08_EC_DETAIL CAL
WHERE X01_SUM <> 0


SELECT ORG_ID
FROM INT_Y08_EC_LIST
