
--DELETE
--FROM PBT_BILL_CREATE
--WHERE COMPANY_CD='X'

INSERT INTO PBT_BILL_CREATE(
COMPANY_CD,
HRTYPE_GBN,
PAY_YM,
PAY_CD,
WRTDPT_CD,
TRDTYP_CD,
BILL_GBN,
ACCNT_CD,
SEQ,
AMT,
TRDTYP_NM,
CUST_CD,
COSTDPT_CD,
ORG_COST_CD,
DEBSER_GBN,
SUMMARY,
BANK_CD,
PAYMTWAY,
PROC_DT,
INPUT_DT,
INPUT_SABUN,
UPDATE_DT,
UPDATE_SABUN
)
SELECT COMPANY,
HRTYPE_GBN,
PAY_YM,
PAY_CD,
--case WHEN PAY_CD = '01' THEN '001' -- 월급여 --> 급여
--	 WHEN PAY_CD = '02' THEN '003' -- 상여 --> 상여
--	 WHEN PAY_CD = '03' THEN '001' -- 사무직급여 -->급여
--	 WHEN PAY_CD = '04' THEN '009' -- 급여소급 --> 소급
--	 WHEN PAY_CD = '05' THEN '003' -- PI수당 -> 상여
--	 WHEN PAY_CD = '06' THEN '002' -- 제수당 -> 제수당
--	 WHEN PAY_CD = '07' THEN '003' -- 인정상여 -> 상여
--     ELSE PAY_CD END,
WRTDPT_CD,
TRDTYP_CD,
BILL_GBN,
ACCNT_CD,
SEQ,
AMT,
TRDTYP_NM,
CUST_CD,
COSTDPT_CD,
ORG_COST_CD,
DEBSER_GBN,
SUMMARY,
BANK_CD,
PAYMTWAY,
PROC_DT,
INPUT_DT,
INPUT_SABUN,
UPDATE_DT,
UPDATE_SABUN
FROM dwehrdev.dbo.PBT_BILL_CREATE
WHERE COMPANY='X'