CREATE OR ALTER VIEW VI_PAY_ACCOUNT_INF_F AS (
SELECT '100' MANDT,
	EMP.SAP_COMPANY_CD AS BUKRS, --	CHAR	회사 코드		4
    EMP.EMP_NO AS SNO, -- 사번
    EMP.EMP_NM AS KNAME, -- 성명
	dbo.F_FRM_DECRYPT_C( EMP.CTZ_NO ) AS JU_NO, -- 주민번호
	EMP.ORG_CD AS DEPTCD,
	dbo.XF_LPAD(dbo.F_PAY_ACC_NO(EMP.EMP_ID, GETDATE(), '01', '2'), 3, '0') AS	BKIND, -- 은행
	REPLACE(REPLACE(dbo.F_FRM_DECRYPT_C(dbo.F_PAY_ACC_NO(EMP.EMP_ID, GETDATE(), '01', '1')),'-',''),' ', '') AS	BANKN, -- 계좌
	EMP.COST_CD AS GUBUN, -- 원천구분
	EMP.COST_NM AS INAME,
	EMP.POS_CD AS ZLEVE,
	EMP.USER_NM AS CHUSER,
	FORMAT(EMP.MOD_DATE, 'yyyyMMdd') AS CHDATE
  FROM VI_INF_PHM_EMP EMP
 WHERE EMP.COMPANY_CD = 'F'
   AND EMP.IN_OFFI_YN = 'Y'
)
