
SELECT *
--DELETE A
  FROM CNV_PAY_WORK A
 WHERE PROGRAM_NM LIKE 'P_CNV_PAY_PAYROL%'
   AND PARAMS LIKE '3,@company_cd=C%'
   --AND FORMAT(STA_TIME, 'yyyyMMdd') = '20210515'
   
   
SELECT A.CNV_PAY_WORK_ID, KEYS, ERR_MSG--, LOG_DATE
--DELETE A
  FROM CNV_PAY_WORK_LOG A
  JOIN CNV_PAY_WORK B
    ON A.CNV_PAY_WORK_ID = B.CNV_PAY_WORK_ID
 WHERE B.PROGRAM_NM LIKE 'P_CNV_PAY_PAYROL%'
   AND B.PARAMS LIKE '3,@company_cd=C%'
   --AND FORMAT(STA_TIME, 'yyyyMMdd') = '20210515'
 

--SELECT *
----DELETE A
--  FROM CNV_PAY_WORK_LOG A
-- WHERE NOT EXISTS(SELECT 1 FROM CNV_PAY_WORK WHERE CNV_PAY_WORK_ID = A.CNV_PAY_WORK_ID)
select *
from PHM_EMP
where COMPANY_CD='S'
and EMP_NO='20210021'