DECLARE @cd_company nvarchar(10) = 'M'
--SELECT YMD.PAY_YM, COUNT(*) AS CNT
--  FROM PAY_PAY_YMD YMD
--  JOIN PAY_PAYROLL PAY
--    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
-- WHERE YMD.COMPANY_CD = @cd_company
-- GROUP BY YMD.PAY_YM
--EXCEPT
--SELECT YM_PAY, COUNT(*) AS CNT
--  FROM dwehrdev.dbo.H_MONTH_PAY_BONUS A
-- WHERE CD_COMPANY = @cd_company
-- GROUP BY YM_PAY

 select ym_pay, SUM(cnt) as cnt
 from (
SELECT YM_PAY, COUNT(*) AS CNT
  FROM dwehrdev.dbo.H_MONTH_PAY_BONUS A
 WHERE CD_COMPANY = @cd_company
   AND YM_PAY >= '201501'
   --AND YM_PAY BETWEEN '202001' AND '202012'
 GROUP BY YM_PAY
 union all
SELECT YM_PAY, COUNT(*) AS CNT
  FROM dwehr_hrd.dbo.H_MONTH_PAY_BONUS A
 WHERE CD_COMPANY = @cd_company
   AND YM_PAY >= '201501'
   --AND YM_PAY BETWEEN '202001' AND '202012'
 GROUP BY YM_PAY
 ) A
 group by YM_PAY
EXCEPT
 SELECT YMD.PAY_YM, COUNT(*) AS CNT
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
 WHERE YMD.COMPANY_CD = @cd_company
   --AND PAY_YM='201912'
   --AND PAY_YM BETWEEN '202001' AND '202012'
 GROUP BY YMD.PAY_YM
 
GO
DECLARE @cd_company nvarchar(10) = 'M'
 SELECT YMD.PAY_YM , COUNT(*) AS CNT
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
 WHERE YMD.COMPANY_CD = @cd_company
  -- AND PAY_YM='202007'
   --AND PAY_YM BETWEEN '202001' AND '202012'
 GROUP BY YMD.PAY_YM 