-- 지급항목확인
DECLARE @cd_company nvarchar(10) = 'W'
SELECT B.ITEM_CD, SUM(A.AMT_ALLOW) AMT
  FROM dwehrdev.dbo.H_MONTH_SUPPLY A
  JOIN CNV_PAY_ITEM B
    ON A.CD_COMPANY = B.COMPANY_CD
   AND A.CD_ALLOW = B.CD_ITEM
 WHERE CD_COMPANY = @cd_company
   AND YM_PAY >= '201701'
   AND YM_PAY <= '202103'
 GROUP BY B.ITEM_CD

EXCEPT

SELECT DTL.PAY_ITEM_CD, SUM(DTL.CAL_MON) AMT
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  JOIN PAY_PAYROLL_DETAIL DTL
    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
 WHERE YMD.COMPANY_CD = @cd_company
   AND YMD.PAY_YM >= '201701'
   AND YMD.PAY_YM <= '202103'
   AND DTL.PAY_ITEM_TYPE_CD = 'PAY_PAY'
   --AND EXISTS (SELECT 1 FROM CNV_PAY_ITEM ITEM
			--	WHERE DTL.PAY_ITEM_CD = ITEM.ITEM_CD
			--   AND YMD.COMPANY_CD = ITEM.COMPANY_CD
			--   AND ITEM.TP_CODE = '1')
 GROUP BY DTL.PAY_ITEM_CD
GO
 -- 공제항목확인
DECLARE @cd_company nvarchar(10) = 'W'
SELECT B.ITEM_CD, SUM(A.AMT_DEDUCT) AMT
  FROM dwehrdev.dbo.H_MONTH_DEDUCT A
  JOIN CNV_PAY_ITEM B
    ON A.CD_COMPANY = B.COMPANY_CD
   AND A.CD_DEDUCT = B.CD_ITEM
 WHERE CD_COMPANY = @cd_company
   AND YM_PAY >= '201501'
   AND YM_PAY <= '202104'
 GROUP BY B.ITEM_CD

EXCEPT

SELECT DTL.PAY_ITEM_CD, SUM(DTL.CAL_MON) AMT
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  JOIN PAY_PAYROLL_DETAIL DTL
    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
 WHERE YMD.COMPANY_CD = @cd_company
   AND YMD.PAY_YM >= '201501'
   AND YMD.PAY_YM <= '202104'
   AND ISNULL(DTL.PAY_ITEM_TYPE_CD,'N/A') IN ('DEDUCT', 'TAX','N/A')
   --AND EXISTS (SELECT 1 FROM CNV_PAY_ITEM ITEM
			--	WHERE DTL.PAY_ITEM_CD = ITEM.ITEM_CD
			--   AND YMD.COMPANY_CD = ITEM.COMPANY_CD
			--   AND ITEM.TP_CODE = '1')
 GROUP BY DTL.PAY_ITEM_CD