SELECT *
FROM CNV_PAY_TYPE2
WHERE COMPANY_CD='W'
;

SELECT *
FROM PHM_EMP_NO_HIS
WHERE COMPANY_CD='W'
AND EMP_NO='20055002'--W,ym_pay=201501,fg_supp=002,dt_prov=20150125,no_person=20055002


DECLARE @cd_company NVARCHAR(10)='S'
      , @ym_pay NVARCHAR(10)='202103'
	  , @fg_supp NVARCHAR(10)='002'
	  , @dt_prov NVARCHAR(10) ='20210325'
	  ,@no_person NVARCHAR(10)='20179005'
SELECT *
FROM dwehrdev.DBO.H_MONTH_SUPPLY A
LEFT OUTER JOIN CNV_PAY_ITEM B
ON A.CD_COMPANY = B.COMPANY_CD
AND A.CD_ALLOW = B.CD_ITEM
WHERE A.CD_COMPANY = @cd_company
AND A.YM_PAY = @ym_pay
AND A.FG_SUPP = @fg_supp
AND A.DT_PROV = @dt_prov
AND A.NO_PERSON = @no_person
AND B.ITEM_CD IS NULL

GO

DECLARE @cd_company NVARCHAR(10)='S'
      , @ym_pay NVARCHAR(10)='202103'
	  , @fg_supp NVARCHAR(10)='002'
	  , @dt_prov NVARCHAR(10) ='20210325'
	  ,@no_person NVARCHAR(10)='20179005'
SELECT *
FROM dwehrdev.DBO.H_MONTH_DEDUCT A
LEFT OUTER JOIN CNV_PAY_ITEM B
ON A.CD_COMPANY = B.COMPANY_CD
AND A.CD_DEDUCT = B.CD_ITEM
WHERE A.CD_COMPANY = @cd_company
AND A.YM_PAY >= @ym_pay
--AND A.FG_SUPP = @fg_supp
--AND A.DT_PROV = @dt_prov
--AND A.NO_PERSON = @no_person
AND B.ITEM_CD IS NULL
SELECT *
FROM CNV_PAY_ITEM
WHERE COMPANY_CD='S'
AND CD_ITEM='999'
