
SELECT dbo.F_PAY_GROUP_CHK(29585705, PAY.EMP_ID, GETDATE()) PAY_GROUP_ID,
		dbo.F_PAY_GROUP_ID(PAY.EMP_ID) PAY_GROUP_ID2,
       *
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  --JOIN PAY_PAYROLL_DETAIL DTL
  --  ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
 WHERE YMD.COMPANY_CD='X'
   --AND DTL.PAY_ITEM_CD='P007' -- 직무수당
   AND PAY_YM = '202103'
   AND PAY.PAY_GROUP_CD = 'X043'
   AND YMD.PAY_YMD BETWEEN '20210301' AND '20210331'

SELECT COUNT(*)
FROM dwehrdev.dbo.H_MONTH_PAY_BONUS
WHERE CD_COMPANY='F'
AND YM_PAY BETWEEN '201602' AND '201602'
AND CD_PAYGP='F21'
--AND CD_PAYGP='X043'

SELECT *
FROM FRM_CODE
WHERE COMPANY_CD='F'
AND CD_KIND='PAY_GROUP_CD'
