
SELECT *
UPDATE DTL
   SET PAY_ITEM_CD = 'D060'
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  JOIN PAY_PAYROLL_DETAIL DTL
    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
 WHERE YMD.COMPANY_CD='F'
   AND DTL.PAY_ITEM_CD='D061' -- 직무수당
   --AND PAY_YM = '202103'
  -- AND PAY.PAY_GROUP_CD = 'X043'
  -- AND YMD.PAY_YMD BETWEEN '20210301' AND '20210331'
;

SELECT *
FROM PAY_ITEM_MST
WHERE COMPANY_CD='F'
--AND PAY_ITEM_CD='D068'
ORDER BY PAY_ITEM_CD