SELECT *
--DELETE A
FROM PAY_TAX_ADD A
--WHERE NOT EXISTS (SELECT 1 FROM PAY_PAY_YMD YMD WHERE YMD.PAY_YMD_ID = A.TAR_PAY_YMD_ID)
--AND NOT EXISTS (SELECT 1 FROM PAY_PAY_YMD YMD WHERE YMD.PAY_YMD_ID = A.PAY_YMD_ID)

SELECT COUNT(*)
--DELETE A
FROM PAY_PAY_YMD_DTL A
JOIN PAY_PAY_YMD B
ON A.PAY_YMD_ID = B.PAY_YMD_ID
--WHERE NOT EXISTS (SELECT 1 FROM PAY_PAY_YMD YMD WHERE YMD.PAY_YMD_ID = A.PAY_YMD_ID)

 SELECT COUNT(*)
 --DELETE B
 FROM PAY_PAY_YMD_DTL_TERM B
 JOIN PAY_PAY_YMD_DTL A
 ON B.PAYYMD_DTL_ID = A.PAYYMD_DTL_ID
 --WHERE NOT EXISTS (SELECT 1 FROM PAY_PAY_YMD_DTL A WHERE A.PAYYMD_DTL_ID = B.PAYYMD_DTL_ID)
