
SELECT *
--UPDATE DTL SET PAY_ITEM_CD = 'PA52'
  FROM PAY_PAY_YMD YMD
  JOIN PAY_PAYROLL PAY
    ON YMD.PAY_YMD_ID = PAY.PAY_YMD_ID
  JOIN PAY_PAYROLL_DETAIL DTL
    ON PAY.PAY_PAYROLL_ID = DTL.PAY_PAYROLL_ID
 WHERE YMD.COMPANY_CD='F'
   AND DTL.PAY_ITEM_CD='P057' -- 보건수당
   --AND PAY_YM = '202103'
  -- AND PAY.PAY_GROUP_CD = 'X043'
  -- AND YMD.PAY_YMD BETWEEN '20210301' AND '20210331'
;
SELECT *
FROM CNV_PAY_DTL_SAP_FINAL
WHERE 1=1
--AND DT_PROV='20161110'
--AND CD_PAYGP='F31'
AND CD_ITEM='3521'
