
WITH H_ORG AS (
		SELECT ORG_ID, MAX(STA_YMD) STA_YMD
		FROM ORM_ORG_HIS
		WHERE STA_YMD <= dbo.XF_LAST_DAY(  '202104'  + '01' )
		GROUP BY ORG_ID
	), T_ORG AS (
		SELECT B.SUPER_ORG_ID, A.ORG_ID, B.ORG_NM, B.ORG_SORT
		  FROM H_ORG A
		  JOIN ORM_ORG_HIS B
		    ON A.ORG_ID = B.ORG_ID
		   AND A.STA_YMD = B.STA_YMD
		  JOIN ORM_ORG C
		    ON B.ORG_ID = C.ORG_ID
	)
SELECT A.*
  FROM dbo.F_PEB_0220( 'H' ,  'KO' ,  '202101' ,  '202104' ,  '10' ,  '10' ,  'N' ) A
  JOIN T_ORG ORG
    ON A.ORG_ID = ORG.ORG_ID
 WHERE A.COMPANY_CD =  'H' 
 ORDER BY ORG.ORG_SORT