USE [dwehrdev_H5]
GO

-- COMPANY_CD 는 수정이 필요할 경우 수정 후 진행하시면 됩니다. ( 주석으로 표시함 [ 기본값 : '01' ] )
-- SEQUENCE 사용은 고객사에 맞게 수정이 필요 합니다.

-- FRM_UNIT_STD_MGR
Insert into FRM_UNIT_STD_MGR (FRM_UNIT_STD_MGR_ID,LOCALE_CD,COMPANY_CD,UNIT_CD,STD_KIND,STD_KIND_NM,CHANGE_YN,MOD_USER_ID,MOD_DATE) 
values (
[ SEQUENCE 함수 ],
'KO',
'01', -- COMPANY_CD
'SPS','SPS_ITEM_CD','간이지급명세항목','Y',9999,GETDATE());

-- FRM_UNIT_ETC
Insert into FRM_UNIT_ETC (FRM_UNIT_STD_MGR_ID,TITLE_NM1,EDIT_FORMAT1,ALIGN1,FORM_EDIT1,MAN_YN1,SQLS1,TITLE_NM2,EDIT_FORMAT2,ALIGN2,FORM_EDIT2,MAN_YN2,SQLS2,TITLE_NM3,EDIT_FORMAT3,ALIGN3,FORM_EDIT3,MAN_YN3,SQLS3,TITLE_NM4,EDIT_FORMAT4,ALIGN4,FORM_EDIT4,MAN_YN4,SQLS4,TITLE_NM5,EDIT_FORMAT5,ALIGN5,FORM_EDIT5,MAN_YN5,SQLS5,NOTE,MOD_USER_ID,MOD_DATE,TZ_CD,TZ_DATE) 
values (
( SELECT FRM_UNIT_STD_MGR_ID FROM FRM_UNIT_STD_MGR WHERE UNIT_CD = 'SPS' AND STD_KIND = 'SPS_ITEM_CD' AND COMPANY_CD = '01' ), -- COMPANY_CD = '01'
null,'1','L','1','N',null,null,'1','L','1','N',null,null,'1','L','1','N',null,null,'1','L','1','N',null,null,'1','L','1','N',null,null,9999,GETDATE(),'KST',GETDATE());

-- FRM_UNIT_STD_ETC
Insert into FRM_UNIT_STD_ETC (FRM_UNIT_STD_MGR_ID,TITLE_NM_K1,EDIT_FORMAT_K1,ALIGN_K1,FORM_EDIT_K1,MAN_YN_K1,SQLS_K1,CD_KIND_K1,TITLE_NM_K2,EDIT_FORMAT_K2,ALIGN_K2,FORM_EDIT_K2,MAN_YN_K2,SQLS_K2,CD_KIND_K2,TITLE_NM_K3,EDIT_FORMAT_K3,ALIGN_K3,FORM_EDIT_K3,MAN_YN_K3,SQLS_K3,CD_KIND_K3,TITLE_NM_K4,EDIT_FORMAT_K4,ALIGN_K4,FORM_EDIT_K4,MAN_YN_K4,SQLS_K4,CD_KIND_K4,TITLE_NM_K5,EDIT_FORMAT_K5,ALIGN_K5,FORM_EDIT_K5,MAN_YN_K5,SQLS_K5,CD_KIND_K5,TITLE_NM_H1,EDIT_FORMAT_H1,ALIGN_H1,FORM_EDIT_H1,MAN_YN_H1,SQLS_H1,CD_KIND_H1,TITLE_NM_H2,EDIT_FORMAT_H2,ALIGN_H2,FORM_EDIT_H2,MAN_YN_H2,SQLS_H2,CD_KIND_H2,TITLE_NM_H3,EDIT_FORMAT_H3,ALIGN_H3,FORM_EDIT_H3,MAN_YN_H3,SQLS_H3,CD_KIND_H3,TITLE_NM_H4,EDIT_FORMAT_H4,ALIGN_H4,FORM_EDIT_H4,MAN_YN_H4,SQLS_H4,CD_KIND_H4,TITLE_NM_H5,EDIT_FORMAT_H5,ALIGN_H5,FORM_EDIT_H5,MAN_YN_H5,SQLS_H5,CD_KIND_H5,TITLE_NM_U1,EDIT_FORMAT_U1,ALIGN_U1,FORM_EDIT_U1,MAN_YN_U1,SQLS_U1,CD_KIND_U1,TITLE_NM_U2,EDIT_FORMAT_U2,ALIGN_U2,FORM_EDIT_U2,MAN_YN_U2,SQLS_U2,CD_KIND_U2,TITLE_NM_U3,EDIT_FORMAT_U3,ALIGN_U3,FORM_EDIT_U3,MAN_YN_U3,SQLS_U3,CD_KIND_U3,TITLE_NM_U4,EDIT_FORMAT_U4,ALIGN_U4,FORM_EDIT_U4,MAN_YN_U4,SQLS_U4,CD_KIND_U4,TITLE_NM_U5,EDIT_FORMAT_U5,ALIGN_U5,FORM_EDIT_U5,MAN_YN_U5,SQLS_U5,CD_KIND_U5,NOTE,MOD_USER_ID,MOD_DATE) 
values (
( SELECT FRM_UNIT_STD_MGR_ID FROM FRM_UNIT_STD_MGR WHERE UNIT_CD = 'SPS' AND STD_KIND = 'SPS_ITEM_CD' AND COMPANY_CD = '01' ), -- COMPANY_CD = '01'
'코드','1','C','2','Y',
'SELECT CD,
       CD_NM
  FROM (
          SELECT DBO.F_FRM_UNIT_STD_VALUE( COMPANY_CD, LOCALE_CD, ''PAY'', ''PAY_ITEM_CD_BASE'', '''', '''', '''', '''', '''', CD, '''', '''', '''', '''', GETDATE(), ''H1'' ) AS PAY_ITEM_TYPE_CD,
                 CD,
                 CD_NM,
                 ORD_NO
            FROM FRM_CODE 
           WHERE CD_KIND =''PAY_ITEM_CD''
           AND COMPANY_CD = ''<<session_company_cd>>''
           AND LOCALE_CD = ''<<session_locale_cd>>''
           AND GETDATE() BETWEEN STA_YMD AND END_YMD
           UNION
          SELECT ''PAY_PAY'' AS PAY_ITEM_TYPE_CD,
                 ''COMM_CD'' AS CD, -- '''' AS CD,
                 ''공통'' AS CD_NM, -- '''' AS CD_NM,
                 ''0'' AS ORD_NO
            FROM DUAL
       ) AS AA
 WHERE PAY_ITEM_TYPE_CD IN (''PAY_PAY'',''PAY_P'')
 ORDER BY ORD_NO',
 null,'신고항목구분','1','L','2','N',
 'SELECT CD     -- 코드                                            
     , CD_NM  -- 코드명                    
  FROM FRM_CODE  -- 공통코드 
 WHERE COMPANY_CD= ''<<session_company_cd>>''
   AND LOCALE_CD = ''<<session_locale_cd>>''
   AND CD_KIND = ''SPS_ITEM_GUBUN''
 ORDER BY ORD_NO',
 null,null,'1','C','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,'1','L','1','N',null,null,null,9999,GETDATE());
