WITH CTE AS(
	SELECT
		SUBSTRING(A.FILE_NAME , PATINDEX ('%\web\%', A.FILE_NAME )-3, 3) AS UNIT
		,A.*
	FROM
		FRM_LABEL_DICTIONARY A
	WHERE LABEL!=LABEL_CODE)
select * from cte 
where unit = 'sce'
order by FILE_NAME