@@FETCH_STATUS -- FETCH의 상태값 0이 성공적
@@TRANCOUNT -- 현재까지의 BEGIN TRANSACTION의 수
   -- COMMIT은 TRANSCTION의 수 -1
   -- ROLLBACK은 @@TRANCOUNT = 0로 만들어 버림
@@ROWCOUNT -- 최근 실행된 문의 영향받은 행의 수, 20억보다 많으면 ROWCOUNT_BIG()사용
@@IDENTITY
@@ERROR
ERROR_NUMBER()
ERROR_MESSAGE()
ERROR_LINE()
ERROR_PROCEDURE()
sysdatetime()
ISNULL(CAST(@for_cur$EMP_ID AS nvarchar(max)), '')
SELECT ISNUMERIC('123'),ISNUMERIC(123),ISNUMERIC('A')

SELECT GETANSINULL(), HOST_ID(), HOST_NAME()