
select DISTINCT KEY_CD1, dbo.F_FRM_CODE_NM( MGR.COMPANY_CD, MGR.LOCALE_CD, 'PAY_ITEM_CD', KEY_CD1, dbo.XF_SYSDATE(0), '1') AS PAY_ITEM_NM -- 급여항목명
  FROM FRM_UNIT_STD_HIS HIS
           , FRM_UNIT_STD_MGR MGR
 WHERE HIS.FRM_UNIT_STD_MGR_ID = MGR.FRM_UNIT_STD_MGR_ID
   AND MGR.UNIT_CD = 'PAY'
   AND MGR.STD_KIND = 'PAY_ITEM_CD_BASE'
      --AND MGR.COMPANY_CD = 'C'
   AND MGR.LOCALE_CD = 'KO'
   AND CD1 LIKE 'BASE_REQ'
ORDER BY KEY_CD1