--SELECT HIS.KEY_CD2 AS CD
--     ,dbo.F_FRM_CODE_NM(MGR.COMPANY_CD, MGR.LOCALE_CD, 'PAY_ITEM_CD', HIS.KEY_CD2, dbo.XF_SYSDATE(0), '1') CD_NM
select *
  FROM FRM_UNIT_STD_HIS HIS
           , FRM_UNIT_STD_MGR MGR
 WHERE HIS.FRM_UNIT_STD_MGR_ID = MGR.FRM_UNIT_STD_MGR_ID
   AND MGR.UNIT_CD = 'REP'
   AND MGR.STD_KIND = 'REP_AVG_MGR_ITEM_CD'
      AND MGR.COMPANY_CD = 'E'
   AND MGR.LOCALE_CD = 'KO'
   --AND HIS.KEY_CD1 = '10'
   AND dbo.XF_SYSDATE(0) BETWEEN HIS.STA_YMD AND HIS.END_YMD