
--SELECT OBJECT_NAME(object_id), OBJECT_DEFINITION(object_id)
--FROM sys.procedures
--WHERE OBJECT_DEFINITION(object_id) LIKE '%CUST_COL2%'
--GO
DECLARE @SEARCH_TEXT NVARCHAR(MAX) = 'CUST_COL2';
 
SELECT B.NAME       AS NAME     -- 이름
     , B.TYPE_DESC  AS TYPE     -- 타입 구분
     , A.DEFINITION AS CONTENTS -- 내용
  FROM SYS.SQL_MODULES A WITH (NOLOCK)
  LEFT JOIN SYS.OBJECTS B WITH (NOLOCK) ON A.OBJECT_ID = B.OBJECT_ID
 WHERE DEFINITION LIKE '%' + @SEARCH_TEXT + '%'      
 ORDER BY TYPE, NAME  
