
--SELECT OBJECT_NAME(object_id), OBJECT_DEFINITION(object_id)
--FROM sys.procedures
--WHERE OBJECT_DEFINITION(object_id) LIKE '%CUST_COL2%'
--GO
DECLARE @검색어 NVARCHAR(MAX) = 'PAY_HOBONG_X';
SET @검색어 = 'F_CNM_PAY_HOBONG_LOEX'
SET @검색어 = 'P_PAY_MST_CHANGE_CNM_X'
SET @검색어 = 'P_PAY_MST_CHANGE_X'
SET @검색어 = 'P_PAY_MST_CHANGE_MAKE'
SET @검색어 = 'F_PEB_GET_VIEW_CD'
SELECT B.NAME       AS NAME     -- 이름
     , B.TYPE_DESC  AS TYPE     -- 타입 구분
     , A.DEFINITION AS CONTENTS -- 내용
  FROM SYS.SQL_MODULES A WITH (NOLOCK)
  LEFT JOIN SYS.OBJECTS B WITH (NOLOCK) ON A.OBJECT_ID = B.OBJECT_ID
 WHERE DEFINITION LIKE '%' + @검색어 + '%'      
 ORDER BY TYPE, NAME  
