USE [dwehrdev]
GO
/****** Object:  StoredProcedure [dbo].[SP_SAPFI_IF_RETRAPP]    Script Date: 2020-11-30 오후 4:15:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROC [dbo].[SP_SAPFI_IF_RETRAPP]
	( @CD_COMPANY VARCHAR(10), @DRAW_DATE CHAR(8), @CD_PAYGP VARCHAR(6),  @REALDATA CHAR(1) ) --@NO_PERSON CHAR(10),
AS
BEGIN
	SET XACT_ABORT ON
	
	-- EXEC SP_SAPFI_IF_RETRAPP 'I', '20110530', 'IA01', 'Y'	


	DECLARE @BUKRS CHAR(4);   --SAP 회사코드
	SET @BUKRS = CASE @CD_COMPANY
	WHEN 'E' THEN 'ET01'
	WHEN 'Q' THEN 'DA01'
	WHEN 'J' THEN 'SJ01'
	WHEN 'M' THEN 'NS01'
	WHEN 'I' THEN 'DR01' ELSE @CD_COMPANY END;
	
	
	--set @BUKRS = case @p_cd_compnay when 'E' then 'ET02' when 'Q' then 'DA01' when 'J' then 'SJ01' when 'M' then 'NS01' when 'I' then 'DR01'
	--	when 'S' then 'FS01' when 'Y' then 'DY01'  when 'O' then 'OL01' when 'L' then 'DWCS' when 'Z' then 'DY01'  
	-- else @p_cd_compnay end;
		
	--INSERT FIIF_F02_ZFITPA01
	--SELECT @BUKRS ,DRAW_DATE, CAST(SEQNO_S AS INT) AS SEQ, CD_COMPANY+SNO AS SNO
	--	, COST_CENTER, SAP_ACCTCODE,AMT,DBCR_GU
	--	, REMARK+'('+SNM+')'
	--	, ACCT_TYPE, ITEM_CODE
	--	, NULL, NULL, NULL, NULL, NULL
	--FROM H_IF_SAPINTERFACE 
	--WHERE CD_COMPANY = @CD_COMPANY AND ACCT_TYPE='E012'
	--	AND SNO = @NO_PERSON AND DRAW_DATE = @DRAW_DATE


	IF @REALDATA != 'Y'
	BEGIN
	
		DELETE FROM SAPFITEST..SAPFITEST.FIIF_F02_ZFITPA01
		WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE  AND GUBUN LIKE 'E012%';
		
		INSERT OPENQUERY(SAPFITEST,'SELECT * FROM FIIF_F02_ZFITPA01')
		SELECT * FROM FIIF_F02_ZFITPA01
		WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE  AND GUBUN LIKE 'E012%'
		ORDER BY SEQNO;

	END
	ELSE
	BEGIN
		IF @CD_COMPANY = 'I'
		BEGIN
		
			IF @CD_PAYGP <> ''
			BEGIN
				DELETE FROM SAPIF_I..DWTEMP.FIIF_F02_ZFITPA01
				WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE  AND GUBUN = 'E012'+@CD_PAYGP;
				
				INSERT OPENQUERY(SAPIF_I,'SELECT * FROM FIIF_F02_ZFITPA01')
				SELECT * FROM FIIF_F02_ZFITPA01
				WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE  AND GUBUN = 'E012'+@CD_PAYGP
				ORDER BY SEQNO;
			END
			ELSE
			BEGIN
				DELETE FROM SAPIF_I..DWTEMP.FIIF_F02_ZFITPA01
				WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE  AND GUBUN LIKE 'E012%';
				
				INSERT OPENQUERY(SAPIF_I,'SELECT * FROM FIIF_F02_ZFITPA01')
				SELECT * FROM FIIF_F02_ZFITPA01
				WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE  AND GUBUN LIKE 'E012%'
				ORDER BY SEQNO;

			END
			
			
		END
		ELSE
		BEGIN
			DELETE FROM SAPFIREAL..SAPFIREAL.FIIF_F02_ZFITPA01
			WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE    AND GUBUN LIKE 'E012%';
			
			INSERT OPENQUERY(SAPFIREAL,'SELECT * FROM FIIF_F02_ZFITPA01')
			SELECT * FROM FIIF_F02_ZFITPA01
			WHERE BUKRS = @BUKRS AND PAYDT = @DRAW_DATE    AND GUBUN LIKE 'E012%'
			ORDER BY SEQNO;
		END
		
	END

	--SELECT * FROM FIIF_F02_ZFITPA01;
	

RETURN

END

